Repository The-Fellowship-of-the-matzip/mat.zip-back, pull requests merged in 2022-08, with the labels that each got.

#59 chore: createDocument 작업 뒤에 JAR 만드는 디렉토리로 옮기는 copyDocument 태스크 추가
  build.gradle
Labels: fix_issue

#63 refactor: 인터셉터 프록시패턴 적용
  src/main/java/com/woowacourse/auth/config/AuthConfig.java
  src/main/java/com/woowacourse/auth/presentation/interceptor/LoginInterceptor.java
  src/main/java/com/woowacourse/auth/presentation/interceptor/PathContainer.java
  src/main/java/com/woowacourse/auth/presentation/interceptor/PathMatcherInterceptor.java
  src/main/java/com/woowacourse/auth/presentation/interceptor/PathMethod.java
  src/main/java/com/woowacourse/auth/presentation/interceptor/RequestPathPattern.java
  src/test/java/com/woowacourse/auth/presentation/interceptor/PathContainerTest.java
  src/test/java/com/woowacourse/auth/presentation/interceptor/PathMethodTest.java
  src/test/java/com/woowacourse/auth/presentation/interceptor/RequestPathPatternTest.java
Labels: authentication, refactor

#68 feat: API의 실행 쿼리 개수를 세는 카운터 구현
  app-external-api/src/main/java/com/woowacourse/support/config/WebConfig.java
  app-external-api/src/main/java/com/woowacourse/support/logging/ApiQueryCounter.java
  app-external-api/src/main/java/com/woowacourse/support/logging/ApiQueryCounterAop.java
  app-external-api/src/main/java/com/woowacourse/support/logging/ApiQueryCountingInterceptor.java
  app-external-api/src/main/java/com/woowacourse/support/logging/ConnectionProxyHandler.java
  app-external-api/src/main/java/com/woowacourse/support/logging/PreparedStatementProxyHandler.java
  app-external-api/src/test/java/com/woowacourse/document/Documentation.java
  app-external-api/src/test/java/com/woowacourse/support/logging/ApiQueryCounterAopTest.java
  app-external-api/src/test/java/com/woowacourse/support/logging/ApiQueryCounterTest.java
  app-external-api/src/test/java/com/woowacourse/support/logging/ConnectionProxyHandlerTest.java
  app-external-api/src/test/java/com/woowacourse/support/logging/PreparedStatementProxyHandlerTest.java
Labels: feature

#67 refactor: 리뷰 조회시 본인이 작성자인지 반환한다.
  app-external-api/src/main/java/com/woowacourse/auth/config/AuthConfig.java
  app-external-api/src/main/java/com/woowacourse/auth/presentation/AuthenticationArgumentResolver.java
  app-external-api/src/main/java/com/woowacourse/auth/presentation/AuthenticationContext.java
  app-external-api/src/main/java/com/woowacourse/auth/presentation/LoginInterceptor.java
  app-external-api/src/main/java/com/woowacourse/auth/presentation/interceptor/LoginCheckerInterceptor.java
  app-external-api/src/main/java/com/woowacourse/auth/presentation/interceptor/LoginInterceptor.java
  app-external-api/src/main/java/com/woowacourse/auth/support/MemberStatus.java
  app-external-api/src/main/java/com/woowacourse/matzip/application/ReviewService.java
  app-external-api/src/main/java/com/woowacourse/matzip/application/response/ReviewResponse.java
  app-external-api/src/main/java/com/woowacourse/matzip/presentation/ReviewController.java
  app-external-api/src/test/java/com/woowacourse/acceptance/ReviewAcceptanceTest.java
  app-external-api/src/test/java/com/woowacourse/acceptance/support/RestAssuredRequest.java
  app-external-api/src/test/java/com/woowacourse/auth/support/MemberStatusTest.java
  app-external-api/src/test/java/com/woowacourse/document/DocumentationFixture.java
  app-external-api/src/test/java/com/woowacourse/document/ReviewDocumentation.java
  app-external-api/src/test/java/com/woowacourse/matzip/application/ReviewServiceTest.java
  app-external-api/src/test/java/com/woowacourse/support/DataClearManager.java
  core/src/main/java/com/woowacourse/matzip/domain/member/Member.java
  core/src/main/java/com/woowacourse/matzip/domain/review/Review.java
  core/src/test/java/com/woowacourse/matzip/domain/member/MemberTest.java
  core/src/test/java/com/woowacourse/matzip/domain/review/ReviewTest.java
Labels: authentication, refactor
