Repository The-Fellowship-of-the-matzip/mat.zip-back, pull requests merged in 2022-07, with the labels that each got.

#53 feat: index.html을 제거하고 gitignore에 추가한다
  .gitignore
  src/main/resources/static/index.html
Labels: fix_issue

#54 infra: Sonar Cloud 코드 분석 도구를 추가한다.
  .github/workflows/backend.yml
  .github/workflows/sonar-cloud-analysis-build.yml
  build.gradle
Labels: infra

#57 style: application 개행 수정
  src/main/java/com/woowacourse/MatzipApplication.java
Labels: fix_issue

#50 refactor: Restaurant 조회 시 정렬 기능 리팩토링
  src/main/java/com/woowacourse/matzip/application/RestaurantService.java
  src/main/java/com/woowacourse/matzip/domain/restaurant/RestaurantFindQueryFactory.java
  src/main/java/com/woowacourse/matzip/domain/restaurant/RestaurantQueryRepository.java
  src/main/java/com/woowacourse/matzip/domain/restaurant/RestaurantRepository.java
  src/main/java/com/woowacourse/matzip/domain/restaurant/SortCondition.java
  src/main/java/com/woowacourse/matzip/presentation/RestaurantController.java
  src/test/java/com/woowacourse/document/RestaurantDocumentation.java
  src/test/java/com/woowacourse/matzip/application/RestaurantServiceTest.java
  src/test/java/com/woowacourse/matzip/domain/restaurant/RestaurantQueryRepositoryTest.java
  src/test/java/com/woowacourse/matzip/domain/restaurant/RestaurantRepositoryTest.java
  src/test/java/com/woowacourse/support/SpringServiceTest.java
Labels: restaurant, refactor
