Repository The-Fellowship-of-the-matzip/mat.zip-back, pull requests merged in 2023-06, with the labels that each got.

#156 feat: 식당 목록 조회시 각 식당의 리뷰 개수 반환
  matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/response/RestaurantTitleResponse.java
  matzip-app-external-api/src/test/java/com/woowacourse/matzip/application/RestaurantServiceTest.java
Labels: feature, restaurant

#158 feat: prod group 설정
  matzip-app-external-api/src/main/resources/application.yml
Labels: fix_issue

#153 feat: 리뷰 작성자의 리뷰 개수 표시 기능
  matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/ReviewService.java
  matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/response/ReviewResponse.java
  matzip-app-external-api/src/test/java/com/woowacourse/acceptance/AcceptanceTest.java
  matzip-app-external-api/src/test/java/com/woowacourse/acceptance/ReviewAcceptanceTest.java
  matzip-app-external-api/src/test/java/com/woowacourse/document/DocumentationFixture.java
  matzip-app-external-api/src/test/java/com/woowacourse/matzip/application/ReviewServiceTest.java
  matzip-app-external-api/src/test/java/com/woowacourse/support/SpringAcceptanceTest.java
  matzip-core/src/main/java/com/woowacourse/matzip/domain/review/ReviewCountByMemberIdDto.java
  matzip-core/src/main/java/com/woowacourse/matzip/domain/review/ReviewCountByMemberIdsDto.java
  matzip-core/src/main/java/com/woowacourse/matzip/domain/review/ReviewRepository.java
  matzip-core/src/test/java/com/woowacourse/matzip/domain/review/ReviewRepositoryTest.java
Labels: feature, review

#166 chore: local phase에서 토큰에 memberId 사용할 수 있도록 수정
  matzip-app-external-api/src/main/java/com/woowacourse/auth/presentation/interceptor/LocalLoginInterceptor.java
  matzip-app-external-api/src/main/java/com/woowacourse/auth/presentation/interceptor/LoginInterceptor.java
  matzip-app-external-api/src/main/java/com/woowacourse/auth/presentation/interceptor/ProdLoginInterceptor.java
  matzip-app-external-api/src/main/resources/data-local.sql
  matzip-app-external-api/src/test/java/com/woowacourse/matzip/application/RestaurantServiceTest.java
  matzip-app-external-api/src/test/java/com/woowacourse/matzip/application/ReviewServiceTest.java
  matzip-app-external-api/src/test/resources/application.yml
  matzip-support/src/main/java/com/woowacourse/matzip/environment/ProfileUtil.java
Labels: authentication

#172 feat: 댓글에 이미지 업로드 기능 추가
  matzip-app-external-api/build.gradle
  matzip-app-external-api/src/main/java/com/woowacourse/auth/config/AuthConfig.java
  matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/ImageService.java
  matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/response/ImageUploadResponse.java
  matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/response/ReviewResponse.java
  matzip-app-external-api/src/main/java/com/woowacourse/matzip/presentation/ImageController.java
  matzip-app-external-api/src/main/java/com/woowacourse/matzip/presentation/request/ReviewCreateRequest.java
  matzip-app-external-api/src/main/java/com/woowacourse/matzip/presentation/request/ReviewUpdateRequest.java
  matzip-app-external-api/src/main/java/com/woowacourse/support/config/S3Config.java
  matzip-app-external-api/src/main/resources/application.yml
  matzip-app-external-api/src/test/java/com/woowacourse/acceptance/ReviewAcceptanceTest.java
  matzip-app-external-api/src/test/java/com/woowacourse/document/DocumentationFixture.java
  matzip-app-external-api/src/test/java/com/woowacourse/document/ReviewDocumentation.java
  matzip-app-external-api/src/test/java/com/woowacourse/matzip/application/ReviewServiceTest.java
  matzip-app-external-api/src/test/resources/application.yml
  matzip-app-external-api/src/test/resources/schema.sql
  matzip-core/src/main/java/com/woowacourse/matzip/domain/image/ImageExtension.java
  matzip-core/src/main/java/com/woowacourse/matzip/domain/review/Review.java
  matzip-core/src/test/java/com/woowacourse/matzip/domain/image/ImageExtensionTest.java
  matzip-core/src/test/java/com/woowacourse/matzip/domain/review/ReviewTest.java
  matzip-core/src/testFixtures/java/com/woowacourse/matzip/ReviewFixtures.java
  matzip-support/src/main/java/com/woowacourse/matzip/exception/UploadFailedException.java
Labels: feature, review

#164 feat: 리뷰 조회시 작성자의 평균 별점 조회
  matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/ReviewService.java
  matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/response/ReviewResponse.java
  matzip-app-external-api/src/test/java/com/woowacourse/acceptance/ReviewAcceptanceTest.java
  matzip-app-external-api/src/test/java/com/woowacourse/document/DocumentationFixture.java
  matzip-core/src/main/java/com/woowacourse/matzip/domain/review/DefaultReviewInfoReviewInfo.java
  matzip-core/src/main/java/com/woowacourse/matzip/domain/review/MemberReviewInfo.java
  matzip-core/src/main/java/com/woowacourse/matzip/domain/review/MemberReviewInfos.java
  matzip-core/src/main/java/com/woowacourse/matzip/domain/review/ReviewCountByMemberIdsDto.java
  matzip-core/src/main/java/com/woowacourse/matzip/domain/review/ReviewRepository.java
  matzip-core/src/test/java/com/woowacourse/matzip/domain/review/ReviewRepositoryTest.java
Labels: feature, review

#165 feat: 북마크(나의 맛집) API 구현 & 북마크 정보 표시
  .gitignore
  matzip-app-external-api/src/docs/asciidoc/bookmark.adoc
  matzip-app-external-api/src/docs/asciidoc/index.adoc
  matzip-app-external-api/src/docs/asciidoc/restaurant.adoc
  matzip-app-external-api/src/main/java/com/woowacourse/auth/config/AuthConfig.java
  matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/BookmarkService.java
  matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/RestaurantService.java
  matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/response/RestaurantResponse.java
  matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/response/RestaurantTitleResponse.java
  matzip-app-external-api/src/main/java/com/woowacourse/matzip/presentation/BookmarkController.java
  matzip-app-external-api/src/main/java/com/woowacourse/matzip/presentation/RestaurantController.java
  matzip-app-external-api/src/main/java/com/woowacourse/support/exception/GlobalControllerAdvice.java
  matzip-app-external-api/src/main/resources/data-local.sql
  matzip-app-external-api/src/main/resources/schema-local.sql
  matzip-app-external-api/src/test/java/com/woowacourse/acceptance/BookmarkAcceptanceTest.java
  matzip-app-external-api/src/test/java/com/woowacourse/acceptance/RestaurantAcceptanceTest.java
  matzip-app-external-api/src/test/java/com/woowacourse/acceptance/support/RestAssuredRequest.java
  matzip-app-external-api/src/test/java/com/woowacourse/document/BookmarkDocumentation.java
  matzip-app-external-api/src/test/java/com/woowacourse/document/Documentation.java
  matzip-app-external-api/src/test/java/com/woowacourse/document/DocumentationFixture.java
  matzip-app-external-api/src/test/java/com/woowacourse/document/RestaurantDocumentation.java
  matzip-app-external-api/src/test/java/com/woowacourse/matzip/application/BookmarkServiceTest.java
  matzip-app-external-api/src/test/java/com/woowacourse/matzip/application/RestaurantServiceTest.java
  matzip-app-external-api/src/test/resources/schema.sql
  matzip-app-external-api/src/test/resources/truncate.sql
  matzip-core/src/main/java/com/woowacourse/matzip/domain/bookmark/Bookmark.java
  matzip-core/src/main/java/com/woowacourse/matzip/domain/bookmark/BookmarkRepository.java
  matzip-core/src/main/java/com/woowacourse/matzip/domain/member/Member.java
  matzip-support/src/main/java/com/woowacourse/matzip/exception/AlreadyBookmarkedException.java
  matzip-support/src/main/java/com/woowacourse/matzip/exception/BookmarkNotFoundException.java
Labels: feature, bookmark

#180 chore: dependabot f/o
  .github/dependabot.yml
Labels: infra

#184 refactor: API 속성명 변경
  matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/RestaurantService.java
  matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/response/RestaurantResponse.java
  matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/response/RestaurantTitleResponse.java
  matzip-app-external-api/src/test/java/com/woowacourse/document/DocumentationFixture.java
  matzip-app-external-api/src/test/java/com/woowacourse/matzip/application/RestaurantServiceTest.java
Labels: refactor, bookmark
